<template>
  <div class="bg-white">
    <div class="mx-auto grid max-w-2xl grid-cols-1 items-center gap-x-8 gap-y-16 px-4 py-12 sm:px-6 lg:max-w-7xl lg:grid-cols-2 lg:px-8">
      <div>
        <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
          {{ category.name }}
        </h2>
        <p class="mt-4 text-gray-500">
          {{ category.description }}
        </p>
        <img
            :src="category.imageUrl"
            :alt="category.setTitle"
            class="rounded-lg bg-gray-100"
        />
      </div>
      <div class="grid grid-cols-2 grid-rows-2 gap-4 sm:gap-6 lg:gap-8">
        <Product
            v-for="product in products"
            :key="product.id"
            :product="product"
            :url="`/catalog/${category.autogeneratedSlug}/product/${product.id}`"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onBeforeMount } from "vue";
import { useShopStore } from "@/stores/ShopStore";
import { useRouter } from "vue-router";

import Product from "@/components/catalog/product/Product.vue";
import { ICategory } from "@/types/ICategory";
import { IProduct } from "@/types/IProduct";

const props = defineProps<{
  categorySlug: string,
}>();

const shopStore = useShopStore();
const router = useRouter();
let category: ICategory | null = null as ICategory;
let products: IProduct[] = [];

onBeforeMount(() => {
  category = shopStore.getCategoryBySlug(props.categorySlug);

  if (!category) {
    router.push({name: '404'});
    return;
  }

  products = shopStore.getCategoryProducts(category.id);
});
</script>
