export interface ICategory {
    autogeneratedSlug: string;
    customSlug: string;
    description: string;
    enabled: boolean;
    hdThumbnailUrl: string;
    id: number;
    imageUrl: string;
    isSampleCategory: boolean;
    name: string;
    productCount: number;
    setTitle: string;
    thumbnailUrl: string;
}
