export interface IProduct {
    id: string;
    autogeneratedSlug: string;
    description: string;
    thumbnailUrl: string;
    inStock: boolean;
    name: string;
    price: number;
    defaultDisplayedPriceFormatted: string;
    categoryIds: number [];
}
