import { defineStore, acceptHMRUpdate } from "pinia";
import shopConfig from "../shopConfig";
import { ICatalogCategories, ICatalogProducts } from "@/types/ICatalog";
import { ICategory } from "@/types/ICategory";
import { IProduct } from "@/types/IProduct";

export const useShopStore = defineStore('ShopStore', {
    state: () => {
        return {
            categories: null as ICatalogCategories | null,
            products: null as ICatalogProducts | null,
            isLoading: true,
        }
    },
    getters: {
        getCategoryBySlug(state){
            return (slug: string): ICategory | null =>
                state.categories.items.find((category) => category.autogeneratedSlug === slug) || null;
        },
        getCategoryProducts(state){
            return (categoryId: number): IProduct[] =>
                state.products.items.filter((product) => product.categoryIds.includes(categoryId))
        },
    },
    actions: {
        async fill() {
            const options = {
                method: 'GET',
                headers: {accept: 'application/json', Authorization: `Bearer ${shopConfig.token}`}
            };

            const [categoriesResponse, productsResponse] = await Promise.all([
                fetch(`https://app.ecwid.com/api/v3/${shopConfig.storeId}/categories`, options),
                fetch(`https://app.ecwid.com/api/v3/${shopConfig.storeId}/products`, options)
            ]);

            this.categories = await categoriesResponse.json();
            this.products = await productsResponse.json();

            this.isLoading = false;
        },
        async getProductById(id: string){
            // @TODO DudnikES Можно сделать fetchHelper или использовать axios для подстановки общих заголовков
            const options = {
                method: 'GET',
                headers: {accept: 'application/json', Authorization: `Bearer ${shopConfig.token}`}
            };

            const response = await fetch(`https://app.ecwid.com/api/v3/${shopConfig.storeId}/products/${id}`, options);
            return await response.json();
        },
    },
});

if (import.meta.hot) {
    import.meta.hot.accept(acceptHMRUpdate(useShopStore, import.meta.hot));
}
